# Generated by Django 3.2.18 on 2023-03-14 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(default='user_<django.db.models.fields.AutoField>', max_length=100)),
                ('user_password', models.CharField(default='123456', max_length=100)),
                ('user_info', models.TextField(default='uhoh，还没有关于该用户的介绍呢~')),
            ],
        ),
    ]
