# Generated by Django 3.2.18 on 2023-03-23 13:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myShop', '0004_activity_activity_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Like',
            fields=[
                ('like_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField()),
                ('activity_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myShop.activity')),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('cart_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField()),
                ('buyer_name', models.CharField(default='', max_length=100)),
                ('getter_name', models.CharField(default='', max_length=100)),
                ('phone', models.CharField(default='', max_length=100)),
                ('seat', models.CharField(default='', max_length=100)),
                ('activity_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myShop.activity')),
            ],
        ),
    ]
